// Use a MutationObserver to watch for changes to the Gmail page
var observer = new MutationObserver(function (mutations) {
  // Check if the "send" button is visible
  var sendButton =
    document.querySelector('[data-tooltip="Send ‪(Ctrl-Enter)‬"]') ||
    document.querySelector('[data-tooltip="Enviar ‪(Ctrl-Enter)‬"]');

  if (sendButton) {
    // The "send" button is visible, so add the new button next to it
    var sendButtonContainer = sendButton.parentNode.parentNode;
    var newButton = document.createElement("div");
    newButton.innerHTML =
      '<div role="button" tabindex="0" class="T-I J-J5-Ji aoO T-I-atl L3" style="user-select: none; margin: 5px;" data-tooltip="Use ChatGPT"><div class="aoq">Use ChatGPT</div></div>';
    sendButtonContainer.insertBefore(
      newButton,
      sendButtonContainer.nextSibling
    );

    // Add an event listener to the new button to handle clicks
    var scribeButton = document.querySelector('[data-tooltip="Use ChatGPT"]');
    if (scribeButton) {
      scribeButton.addEventListener("click", function () {
        // Get the text content of the Gmail compose window and the email conversation
        var composeWindow =
          document.querySelector(".Am.Al.editable.LW-avf") ||
          document.querySelector(".editable.LW-avf");
        var conversation =
          document.querySelector(".ii.gt") ||
          document.querySelector(".ii.gt.adP.adO");

        var prompt = "";
        if (composeWindow && composeWindow.innerText) {
          // Add a heading before the email conversation
          prompt =
            "Consider the previous email exchange:\n" + conversation.innerText;

          // Insert the instructions after the previous conversation
          prompt +=
            "\n\nWrite a response email paraphrasing the following:\n" +
            composeWindow.innerText;

          console.log(prompt);

          // Clear the text content of the compose window
          composeWindow.innerText = "\n";
        }

        // Show a spinner while the request is being processed
        scribeButton.innerHTML =
          '<div role="button" tabindex="0" class="T-I J-J5-Ji aoO T-I-atl L3" style="user-select: none; margin: 5px;" data-tooltip="Use ChatGPT"><div class="aoq">Loading...</div></div>';

        // Send a message to the background script to get a response from ChatGPT
        chrome.runtime.sendMessage(
          { type: "generate-text", prompt: prompt },
          function (response) {
            // Check if the response is an error
            if (response.type === "error") {
              // Show an error message to the user
              scribeButton.innerHTML = '<div class="aoq">Error</div>';
            } else {
              // Insert the generated text into the Gmail compose window
              if (composeWindow && composeWindow.innerText) {
                // The compose window exists and has text content, so append the generated text to its text
                composeWindow.innerHTML += "<p>" + response.text + "</p>";

                // Append the message indicating that the email was generated by ChatGPT
                composeWindow.innerHTML +=
                  "<p>This email was entirely generated by ChatGPT.</p>";

                scribeButton.innerHTML =
                  '<div role="button" tabindex="0" class="T-I J-J5-Ji aoO T-I-atl L3" style="user-select: none; margin: 5px;" data-tooltip="Use ChatGPT"><div class="aoq">Use ChatGPT</div></div>';
              }
            }
          }
        );
      });
    }

    // Stop observing the page
    console.log("disconnecting");
    observer.disconnect();
  }
});

// Start observing the Gmail page
var target = document.querySelector("html");
observer.observe(target, { childList: true, subtree: true });
